[build]
  base = "/"
  publish = "/public"

[build.environment]
  NODE_VERSION = "23.5.0"
  TZ = "Asia/Tokyo"

[[redirects]]
from = "/post/-1"
to = "/post/23"

[[redirects]]
from = "/recommends"
to = "/recommended-posts"
status = 301